name: Test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    container: tunathu/thuthesis-test-env

    steps:
    - uses: actions/checkout@v1
    - name: Test thesis
      run: make thesis
    - name: Test spine
      run: make spine
    - name: Test doc
      run: make doc
    - name: l3build check
      run: make test
